In [2]:
from google.colab import drive
drive.mount('/content/drive')

project_path="/content/drive/MyDrive/Retail_EDA_Project/"

import pandas as pd

df= pd.read_csv(project_path+"Data/Processed/cleaned_superstore.csv")

Mounted at /content/drive

In [3]:
df.head()

,Ship Mode,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,Henderson,Kentucky,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,Henderson,Kentucky,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,Los Angeles,California,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,Fort Lauderdale,Florida,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,Fort Lauderdale,Florida,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [4]:
#Profit Margin Feature
df['Profit Margin'] = (df['Profit']/df['Sales'])*100

In [5]:
#Discount Category
def discount_category(x):
  if x==0:
    return 'No Discount'
  elif x <= 0.2:
    return 'Low Discount'
  elif x <=0.4:
    return 'Medium discount'
  else:
    return 'High Discount'

df['Discount Category']= df['Discount'].apply(discount_category)

In [6]:
#Loss Flag
df['Loss Flag']= df['Profit'].apply(
    lambda x: 'Loss' if x<0 else 'Profit'
)

In [7]:
df.head()

,Ship Mode,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Profit Margin,Discount Category,Loss Flag
0,Second Class,Consumer,Henderson,Kentucky,South,Furniture,Bookcases,261.9600,2,0.00,41.9136,16.00,No Discount,Profit
1,Second Class,Consumer,Henderson,Kentucky,South,Furniture,Chairs,731.9400,3,0.00,219.5820,30.00,No Discount,Profit
2,Second Class,Corporate,Los Angeles,California,West,Office Supplies,Labels,14.6200,2,0.00,6.8714,47.00,No Discount,Profit
3,Standard Class,Consumer,Fort Lauderdale,Florida,South,Furniture,Tables,957.5775,5,0.45,-383.0310,-40.00,High Discount,Loss
4,Standard Class,Consumer,Fort Lauderdale,Florida,South,Office Supplies,Storage,22.3680,2,0.20,2.5164,11.25,Low Discount,Profit

In [8]:
df.to_csv('/content/drive/MyDrive/Retail_EDA_Project/Data/Processed/cleaned_superstore.csv', index=False)